services:
  backend:
    build:
      context: ../../
      dockerfile: docker/n-t-ai-system/backend/Dockerfile
    container_name: ntai-backend
    ports:
      - "8000:8000"
    volumes:
      - ../../backend:/app
    environment:
      - PROJECT_NAME=N-T-AI-System
    restart: unless-stopped

  frontend:
    build:
      context: ../../
      dockerfile: docker/n-t-ai-system/frontend/Dockerfile
    container_name: ntai-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
